### PR TITLE
Changes to fix low node utilization strategy

### LINKED ISSUE #42: Nodes with scheduling disabled should not be taken into consideration for LowNodeUtilization
I have the following nodes -

```console
$ kubectl get nodes
NAME                           STATUS                     ROLES     AGE       VERSION
kubernetes-master              Ready,SchedulingDisabled   <none>    56m       v1.8.4-dirty
kubernetes-minion-group-5rrh   Ready                      <none>    56m       v1.8.4-dirty
kubernetes-minion-group-fb8c   Ready                      <none>    56m       v1.8.4-dirty
kubernetes-minion-group-t1r3   Ready,SchedulingDisabled   <none>    56m       v1.8.4-dirty
```

The worker node `kubernetes-minion-group-t1r3` was cordoned and marked as unschedulable, however it fulfilled the criteria for being an underutilized node according to the following policy file -

```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "LowNodeUtilization":
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:  # any node below the following percentages is considered underutilized
           "cpu" : 40
           "memory": 40
           "pods": 40
         targetThresholds: # any node above the following percentages is considered overutilized
           "cpu" : 30
           "memory": 2
           "pods": 1
```

When I ran the descheduler, `kubernetes-minion-group-t1r3` (the cordoned node) was taken into account and marked as underutilized and multiple pods were evicted from other nodes in the hope that the scheduler will schedule on `kubernetes-minion-group-t1r3`, but that never happened since the node was cordoned.

Does it make sense to not take a cordoned node into consideration while looking for underutilized nodes?

I ran the descheduler like the following -

```console
$ _output/bin/descheduler --kubeconfig-file /var/run/kubernetes/admin.kubeconfig --policy-config-file examples/custom.yaml -v 5 
I1125 18:58:46.014381    2813 reflector.go:198] Starting reflector *v1.Node (1h0m0s) from github.com/kubernetes-incubator/descheduler/pkg/descheduler/node/node.go:83
I1125 18:58:46.016167    2813 node.go:50] node lister returned empty list, now fetch directly
I1125 18:58:46.017010    2813 reflector.go:236] Listing and watching *v1.Node from github.com/kubernetes-incubator/descheduler/pkg/descheduler/node/node.go:83
I1125 18:58:47.834184    2813 lownodeutilization.go:115] Node "kubernetes-master" usage: api.ResourceThresholds{"cpu":95, "memory":11.575631035804197, "pods":8.181818181818182}
I1125 18:58:47.834986    2813 lownodeutilization.go:115] Node "kubernetes-minion-group-5rrh" usage: api.ResourceThresholds{"cpu":90.5, "memory":6.932161992316314, "pods":17.272727272727273}
I1125 18:58:47.835701    2813 lownodeutilization.go:115] Node "kubernetes-minion-group-fb8c" usage: api.ResourceThresholds{"cpu":96.5, "memory":14.0975556030657, "pods":17.272727272727273}
I1125 18:58:47.835783    2813 lownodeutilization.go:115] Node "kubernetes-minion-group-t1r3" usage: api.ResourceThresholds{"cpu":10, "memory":2.764226588836412, "pods":1.8181818181818181}
I1125 18:58:47.835819    2813 lownodeutilization.go:163] evicting pods from node "kubernetes-minion-group-fb8c" with usage: api.ResourceThresholds{"cpu":96.5, "memory":14.0975556030657, "pods":17.272727272727273}
I1125 18:58:48.096681    2813 lownodeutilization.go:194] Evicted pod: "database-6f97f65956-6pxp5" (<nil>)
I1125 18:58:48.098323    2813 lownodeutilization.go:208] updated node usage: api.ResourceThresholds{"cpu":91.5, "memory":14.0975556030657, "pods":16.363636363636363}
I1125 18:58:48.361411    2813 lownodeutilization.go:194] Evicted pod: "wordpress-57f4bb46bf-g27k6" (<nil>)
I1125 18:58:48.361522    2813 lownodeutilization.go:208] updated node usage: api.ResourceThresholds{"cpu":86.5, "memory":14.0975556030657, "pods":15.454545454545455}
I1125 18:58:48.623304    2813 lownodeutilization.go:194] Evicted pod: "wordpress-57f4bb46bf-m62cm" (<nil>)
I1125 18:58:48.623330    2813 lownodeutilization.go:208] updated node usage: api.ResourceThresholds{"cpu":81.5, "memory":14.0975556030657, "pods":14.545454545454547}
I1125 18:58:48.894712    2813 lownodeutilization.go:194] Evicted pod: "wordpress-57f4bb46bf-mblx7" (<nil>)
I1125 18:58:48.894832    2813 lownodeutilization.go:208] updated node usage: api.ResourceThresholds{"cpu":76.5, "memory":14.0975556030657, "pods":13.636363636363638}
I1125 18:58:48.894991    2813 lownodeutilization.go:163] evicting pods from node "kubernetes-master" with usage: api.ResourceThresholds{"cpu":95, "memory":11.575631035804197, "pods":8.181818181818182}
I1125 18:58:48.895063    2813 lownodeutilization.go:163] evicting pods from node "kubernetes-minion-group-5rrh" with usage: api.ResourceThresholds{"cpu":90.5, "memory":6.932161992316314, "pods":17.272727272727273}
```

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4-dirty", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"dirty", BuildDate:"2017-11-25T12:04:44Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.4-dirty", GitCommit:"9befc2b8928a9426501d3bf62f72849d5cbcd5a3", GitTreeState:"dirty", BuildDate:"2017-11-25T11:54:10Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
/cc @aveshagarwal @containscafeine - This should fix #42

### CODE REVIEW

File: pkg/descheduler/strategies/lownodeutilization.go [hunk 1]
```diff
@@ -109,25 +109,39 @@ func validateTargetThresholds(targetThresholds api.ResourceThresholds) bool {
 	return true
 }
 
-func classifyNodes(npm NodePodsMap, thresholds api.ResourceThresholds, targetThresholds api.ResourceThresholds) ([]NodeUsageMap, []NodeUsageMap, []NodeUsageMap) {
-	lowNodes, targetNodes, otherNodes := []NodeUsageMap{}, []NodeUsageMap{}, []NodeUsageMap{}
+// isNodeUschedulable checks if the node is unschedulable. This is helper function to check only in case of
+// underutilized node so that they won't be accounted for.
+func isNodeUschedulable(node *v1.Node) bool {
```
Comment (aveshagarwal) [inline pkg/descheduler/strategies/lownodeutilization.go]: move it to https://github.com/kubernetes-incubator/descheduler/blob/master/pkg/descheduler/node/node.go?

**Comment by aveshagarwal** [comment]
one comment otherwise lgtm.

File: pkg/descheduler/strategies/lownodeutilization.go (hunk 1 above)
Comment (ravisantoshgudimetla) [reply pkg/descheduler/strategies/lownodeutilization.go]: Makes sense. Moved it there.

File: pkg/descheduler/node/node.go [hunk 2]
```diff
@@ -86,6 +86,7 @@ func GetNodeLister(client clientset.Interface, stopChannel <-chan struct{}) core
 	return nodeLister
 }
 
+// IsReady checks if the descheduler could run against give node.
```
Comment (aveshagarwal) [inline pkg/descheduler/node/node.go]: nit: just noticed so you might want to rephrase this "give node"?

Comment (ravisantoshgudimetla) [reply pkg/descheduler/node/node.go]: Done. Thanks for catching it.

File: pkg/descheduler/node/node.go [hunk 3]
```diff
@@ -111,3 +112,17 @@ func IsReady(node *v1.Node) bool {
...
 }
+
+// IsNodeUschedulable checks if the node is unschedulable. This is helper function to check only in case of
+// underutilized node so that they won't be accounted for.
+func IsNodeUschedulable(node *v1.Node) bool {
+	if node.Spec.Unschedulable {
+		return true
+	}
+	for _, taint := range node.Spec.Taints {
+		if taint.Effect == v1.TaintEffectNoSchedule {
```
Comment (aveshagarwal) [inline pkg/descheduler/node/node.go]: sorry, just noticed this. This is not true as some pods that tolerate that NoSchedule taint can still be scheduled, or unless we find a way in upstream to make node unschedulable using some standard taint where no pod could tolerate that taint. Its better to remove this.

Comment (ravisantoshgudimetla) [reply pkg/descheduler/node/node.go]: You are right when it comes to NoSchedule taint but this is what node controller and kubeadm are using. I believe the idea is to slowly move away from Unschedulable field in nodeSpec. So, to be in sync with upstream community, I think it would be better to respect `NoSchedule` taint but add a TODO saying that its not proper UnSchedulable field. WDYT?

Comment (aveshagarwal) [reply pkg/descheduler/node/node.go]: No that does not seem correct. Not sure what you mean by " this is what node controller and kubeadm are using. "? Are they using some taint to declare a node as Unschedulable? if yes, could you point me to that? As I said, without having a NoSchedule taint that "no pod" can tolerate, we can not use NoSchedule taint as an indicator for Unschedulable. Also  not sure what do you mean by " to be in sync with upstream community"? I really want to be in sync, but only if there is a solution upstream.

Comment (ravisantoshgudimetla) [reply pkg/descheduler/node/node.go]: I agree with you that it is not the correct way to do it and I believe you created an issue upstream for it. But kubeadm moved to taint for master(https://github.com/kubernetes/kubernetes/pull/41835/files). I just created a cluster using kubeadm and the master just has label and a NoSchedule taint. No Unschedulable field, if we go with our current approach, we will take nodes with NoSchedule taint into account as well. 

```
Name:			descheduler-54486c3a-c257-11e7-a71e-c85b76333877
Role:			
Labels:			beta.kubernetes.io/arch=amd64
			beta.kubernetes.io/os=linux
			kubernetes.io/hostname=descheduler-54486c3a-c257-11e7-a71e-c85b76333877
			node-role.kubernetes.io/master=
Annotations:		node.alpha.kubernetes.io/ttl=0
			volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:			node-role.kubernetes.io/master:NoSchedule
CreationTimestamp:	Sun, 05 Nov 2017 13:33:00 -0500
Conditions:
```

I am fine with either with/without NoSchedule Taint.

Comment (aveshagarwal) [reply pkg/descheduler/node/node.go]: you also need to check if they are not allowing pods to set "node-role.kubernetes.io/master:NoSchedule" via admission controller or some other means. Anyway we can *NOT* consider *any* NoSchedule taint for Unschedulable something this PR does so its better to remove that check.

**Comment by ravisantoshgudimetla** [comment]
Done @aveshagarwal. PTAL.
